package server;

public enum Endpoint {
    GET_TASKS,
    GET_TASKS_ID,
    POST_TASKS,
    DELETE_TASKS_ID,
    GET_SUBTASKS,
    GET_SUBTASKS_ID,
    POST_SUBTASKS,
    DELETE_SUBTASKS_ID,
    GET_EPICS,
    GET_EPICS_ID,
    POST_EPICS,
    DELETE_EPICS_ID,
    GET_HISTORY,
    GET_PRIORITIZED,
    UNKNOWN
}
